# Generated by Django 5.0.6 on 2024-09-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
